### ISSUE TITLE
ChromeIPass does not work with 2-page authentication sites

### ISSUE THREAD

**Issue by alensiljak** [pfn/passifox#114]
Some e-banking sites have authentication split into two pages. Hence the first page does not contain a password field. For this reason, the ChromeIPass hides the icon and does not provide an option to fill the field(s) on the page.
With KeePass, I usually have two entries to work around this and it functions OK. 
Now, I'd like to get the same behaviour from a browser plugin. 
Additional problem is that right-click is disabled on some of these pages (HSBC, for example) so functionality through icon-clicking would be preferable to a page context menu.

**Comment by fritzophrenic** [comment]
This issue still exists, and as @MisterY pointed out, nothing happens at all when the hotkey is pressed, apparently because the username and password field combination is not present on a single page. I can right-click the field and tell chromeipass to "fill user+pass" and that works, as long as I have set up the KeePass entry manually already. However, it does not seem possible to *create* a KeePass entry from chromeipass, if the login takes multiple pages. I needed to create two separate entries (one for each page of the login), and I needed to do it manually.

**Comment by krzemian** [comment]
I was able to configure two-page authentication by manually creating an entry in KeePass and manually pinpoint Username field in ChromeIPass at https://www.centrum24.pl/centrum24-web/login
At the same time I'm unable to configure ChromeIPass this way at https://online.t-mobilebankowe.pl/ib/login.html

My hypothesis is that the problem stems from the fact that both Username and Password pages have the same url (https://online.t-mobilebankowe.pl/ib/login.html).

Do you see a way out?

**Comment by fritzophrenic** [comment]
As a workaround, you can attempt to configure a set of auto-type sequences in KeePass itself. It's not very user-friendly though.

**Comment by fritzophrenic** [comment]
@pfn Can this issue be re-opened? It doesn't seem to be resolved. Or is there another existing issue for multi-page logins?

**Comment by pfn** [comment]
There is no solution and probably will never be one.

And as such, it does work in a basic fashion: fill username on first page
and fill password on second

--

**Comment by fritzophrenic** [comment]
How would one fill the Username on the first page? As mentioned in comments, chromeIPass does not detect the first page at all; there are no fill-in options and the shortcut does nothing. I understand KeeFox has a "start recording" button for manually specifying such logins, maybe chromeIPass could do something similar?

**Comment by pfn** [comment]
Right click fill user + pass

--

**Comment by fritzophrenic** [comment]
OK I forgot that will work, assuming one has already created one or more entries in KeePass. But right now this must be done manually, and it must be done in a way keepasshttp can find it. This is very user-unfriendly; I still think chromeIPass should support creating multi-page configurations somehow.

**Comment by waynebloss** [comment]
+1 for supporting multi-page login. I really wish Google and other sites wouldn't use multiple pages for login, but it doesn't seem like they're going to stop.

I've never seen the "specify your own credentials" feature actually work, but I'd imagine that if it did work then that would be the key to getting multi-page to work, right?

**Comment by waynebloss** [comment]
Also, it's even worse for people with multiple accounts. Here's my experience signing into Gmail:

- Open gmail.com in an incognito window.
- Redirected to sign-in.
- Right-click empty Username field, click ChromeIPass -> Fill User + Pass.
- Modal dialog pops up telling me I have multiple accounts (thanks!)
- Click OK on the dialog.
- Now, I can finally see the drop-down with my account names.
- Choose the account I want to login with.
- Click Next.
- Password is already filled in (so happy!!)
- Click Signin.
