### ISSUE TITLE
Annoying "KeePassHttp is not running" warning

### ISSUE THREAD

**Issue by sinancetinkaya** [pfn/passifox#227]
I don't have KeePass always running. While KeePass is not running, passifox keeps saying "KeePassHttp is not running".
Why is there no option to turn it off?
![2013-11-27 16_17_37-passifox __ add-ons for firefox](https://f.cloud.github.com/assets/2675655/1631871/ebb1678c-576e-11e3-9468-8f6b6dfad7a9.png)
![2013-11-27 16_18_47-add-ons manager](https://f.cloud.github.com/assets/2675655/1631872/ebb404ce-576e-11e3-8f93-77c1ce7cdc6e.png)

**Comment by HeyZiko** [comment]
Although this is closed and kinda old, I also find this especially annoying because it kicks in after the page loads, causing my clicking to miss the mark. @sinancetinkaya, I don't see your fork in the network, would you mind sharing your fix with a gist?

**Comment by sinancetinkaya** [comment]
If I remember correctly, I didn't fix this bug. I just turned off the notification pop-up.
Open up KeePassFox.jsm inside passifox.xpi/modules
comment out the line below by adding //
this._showNotification("KeePassHttp is not running", null,"kpf-running-note");

**Comment by braincow** [comment]
I forked, I branched and I created a simple configuration workaround for this issue. Lets just hope that the developer sees my code worthy of a pull: https://github.com/pfn/passifox/pull/449
