### ISSUE TITLE
Donate

### ISSUE THREAD

**Issue by christ-off** [pfn/passifox#234]
Dear Perry Nguyen and Lukas Schulze
Could you setup a Donate or Flattr button somewhere to reward you ?

Regards 

Christopher

**Comment by pligor** [comment]
You don't have to include a flattr button anywhere. You just setup your flattr account and if someone gives you a star (the stars like this repository currently has 343) then you get flattred! I received some money one day from one of my contributions without expecting it and the feeling of reward was good!
