### ISSUE TITLE
Keyboard shortcut

### ISSUE THREAD

**Issue by steven26** [pfn/passifox#292]
Dear sir,

I am using passifox 1.1.11 in Firefox 31.0 on a Mac.
It seems that the keyboard shortcuts (ctrl + shift +U, ctrl + shift +P) are not working
and these shortcuts are doing nothing.

Is there any way tho get these shortcuts working?

Kind regards,

Steven

**Comment by nowottnya** [comment]
I'm also using Firefox, but the solution from #213 only works in Chrome (shortcuts: ctrl+shift+F6 for username and password and ctrl+shift+F1 for password only)

OS: Windows 7
PassIFox Version: 1.1.13
KeePassHttp Version: 1.8.4.0
Firefox Version: 39.0
KeePass: 2.23

So currently there is not workaround to use the shortcut in Firefox?
