### ISSUE TITLE
Issue with Splunk v6.2 and Chrome iPass

### ISSUE THREAD

**Issue by MiddleSiggy** [pfn/passifox#318]
chromeIPass Version:2.6.7
KeePassHttp Version:1.8.3.0

After the latest Splunk upgrade to version 6.2, the integration between keepass and keepasshttp are no longer working correctly with the Splunk loging screen.

What happens is the username and password fields get filled in, but during submission, the page does not send the values. So the tool must not be able to place the correct field in the right spots.

This is what is sent in the POST communication:
cval=2021369897&username=&password=&return_to=%2Fen-US%2F 

Notice how username and password contain no information.

**Comment by ghost** [comment]
I guess the point is that the Splunk log in page does check for user input. There are more sites that also behave like that. 

A workaround (but no solution to this issue) is to tab through the fields, add and delete a character at the end of the filled in username and password values. After that procedure, the submission of the credentials works. 

I also tried to circumvent this behaviour by configuring a custom fill-in pattern, but also without success.

The method this plugin and als KeeFox (for Firefox) use to prefill the login fields, are not detected as user interactions by the JavaScript of the login pages.
