### ISSUE TITLE
chromeIPass issue with KeepassHttp 1.8.4.0 - Windows 8.1

### ISSUE THREAD

**Issue by SuperITMan** [pfn/passifox#337]
Hello, 

Since last update of keepasshttp, I cannot use combinaisons Ctrl + Shift + U for auto-complete. It doesn't do nothing.
I have to enable auto-complete always option in chromeIPass. But sometimes I don't want auto-complete...

I'm on Windows 8.1 pro x64 and with before version of keepasshttp, it works normally. 

Is it possible to find any solution ? 

Thanks in advance for your answer, 

Thank you very much for this utility ! :) 

Regards, 

SuperITMan

**Comment by ragnarkarlsson** [comment]
I to am experiencing this issue, exact same setup as scardus above.

**Comment by clementko** [comment]
I have the exact same issue after updated KeepassHttp to 1.8.4.0

chromePass icon always display question mark when the site is matched. Manually clicking the chromePass icon and select the entry(only 1) will send the user and password to the right field 

Clement

**Comment by tomsykes** [comment]
I'm getting this in windows 7 too. Has only been since the move to 1.8.4

**Comment by abhikush** [comment]
I have this issue as well.

**Comment by abhikush** [comment]
This is probably the same as #347 and #341, which have been fixed (but latest version is not yet in chrome webstore)

**Comment by SuperITMan** [comment]
Many thanks for info abhikush ! :)
It works perfectly !

I downloaded chromeipass directory on github -> https://github.com/pfn/passifox and download as zip. Then I unziped the zip downloaded.
Finally, I actived dev mode in Chrome and I "Load unpacked extension..." and I selected directory chromeipass. 

Thanks to devs ! :)

**Comment by primetime4x4** [comment]
This has been a source of frustration for awhile, but I found a workaround for the current published extension.

Use these keyboard shortcuts as replacements:
ctrl+shift+F6 (user & password)
ctrl+shift+F1 (password only)

References:
[c5d74cd](https://github.com/pfn/passifox/commit/c5d74cd9210e54c149d855967ec8f195ca69df47?diff=unified)
[javascript char codes](http://www.cambiaresearch.com/articles/15/javascript-char-codes-key-codes)

**Comment by abhikush** [comment]
Thank You primetime4x4. This works well.

**Comment by pfn** [comment]
51e842b
