### ISSUE TITLE
Chrome iPass duplicate popup error after installing KeepassHttp -SOLVED 

### ISSUE THREAD

**Issue by VWFeature** [pfn/passifox#338]
Started immediately after install of 1.8.4.0 
In short:
I got the "Do you really have only one installation.." popup, but there's only one .plgx of 154kb in the KP directory tree. There's no .dll of 154kb either.  

There IS a KeepassHttp.dll file in the mono subdirectory.
Renamed the KeepassHttp.dll file in the mono subdirectory to KeepassHttp.olddll. Phantom copy of KeepassHttp gone, no error message, now working.  
= Recommended solution. 
********************************************************************
Long version= how I got there:
I got the "Do you really have only one installation.." popup, but there's only one .plgx of 154kb in the KP directory tree. There's no .dll of 154kb either.  There IS a KeepassHttp.dll file in the mono subdirectory.
https://www.dropbox.com/s/bgyqe0cou05imw8/Screenshot%202014-12-29%2011.20.08.png?dl=0

Looking in the KP 'Tools'  tab, I have TWO instances of KeepassHttp in plugins and two  instances of 'KeepassHttp options'.

I tried changing the port#- still conflicts. 
I removed all the KeepassHttp files from the KP directory, purged the cache, disabled plugins, restarted KP-starts ok, no errors, but still shows KeepassHttp as plugin- though no KeepassHttp files in directory!
Disabled KeepassHttp (ChromeiPass) in Chrome- restarted Chrome & KP, STILL shows (one, not working)  KeepassHttp plugin and KeepassHttp options!

I finally purged the phantom copy of KeepassHttp from KP by removing the KeepassHttp.dll file from the mono subdirectory.
Uninstalled all KeepassHttp files and directories, reinstalled in subdirectory- doesn't work, but does show duplicate entries.  It's Baaaaack!

Renamed the KeepassHttp.dll file in the mono subdirectory to KeepassHttp.notdll. Phantom copy of KeepassHttp gone, but still not working.  

Moved all  KeepassHttp files to (read only) Keepass directory, shows error popup, duplicate KeepassHttp options entries and plugin, but working.

Renamed the KeepassHttp.dll file in the mono subdirectory to KeepassHttp.olddll. Phantom copy of KeepassHttp gone, no error message, now working. 

Thanks to the wizards who create and understand these wonders. 

Win 7 64 /Chrome Version 39.0.2171.95 m / Keepass 2.28

**Comment by backspace** [comment]
If your issue is resolved, it would be helpful to maintainers for you to close the issue.
