### ISSUE TITLE
ChromeIPass: CTRL-SHIFT-P opens chrome print dialog

### ISSUE THREAD

**Issue by abhikush** [pfn/passifox#341]
Instead of filling password, CTRL-SHIFT-P opens chrome's print dialog.

**Comment by chrahunt** [comment]
What version of Chrome are you using? I was not able to replicate this in Chrome 41-dev with chromeIPass 2.6.7.

**Comment by timlewis-promedica** [comment]
I'm getting the issue with the latest release version of Chrome on Windows 7 -- "Version 40.0.2214.91 m"

**Comment by bjohanso** [comment]
I'm seeing the same problem across three different Windows 7 Professional machines running Chrome Version 40.0.2214.91 m.  Ctrl-Shift-P brings up the Windows System Print dialog (not Chrome's custom print system).  Ctrl-Shift-U does nothing.  To fill in the password I now have to right-click and choose the menu option.  This is on ChromeIPass 2.6.8 and KeePassHttp 1.8.4.0, BTW.

**Comment by chrahunt** [comment]
Turns out this is a duplicate of #347, and should be fixed in c5d74cd.

**Comment by abhikush** [comment]
How do I download the latest version with this fix? The version in chrome webstore is still 2.6.8
