### ISSUE TITLE
chromeIPass fails to detect all entry fields on https://gbg.onlinedisclosures.co.uk/

### ISSUE THREAD

**Issue by cmt29** [pfn/passifox#345]
I can't seem to get chromeIPass to detect the first entry field on the login at this website: https://gbg.onlinedisclosures.co.uk/. I've programmed a custom field in KeePass2 giving it the required "KPH: " prefix, and modified the keepasshttp settings to allow the use of custom fields. But I can't seem to select the first PIN field when choosing own credentials for the page, nor is it detected automatically. What might I be doing wrong?

Thanks.

**Comment by chrahunt** [comment]
You aren't doing anything wrong. The field type 'number' isn't one that chromeIPass recognizes. I've made a fix and will submit a pull request to solve this.

**Comment by cmt29** [comment]
Thanks very much for your response.

I am also having problems with this site:
http://hazelwood.clubsolution.co.uk/proc_intro.asp

I can never get both fields to be recognised.
