### ISSUE TITLE
chromeIPass shortcuts stopped working

### ISSUE THREAD

**Issue by Fostenel** [pfn/passifox#347]
chromeIPass Version:2.6.8
KeePassHttp Version:1.8.4.0
Chrome Version 39.0.2171.95 m
KeyPass 2.28

Ctrl+Shift+U no longer works, and Ctrl+Shift+P brings up a print dialog.  This started happening within the last week.

**Comment by Majesty00** [comment]
OS: Windows 7
chromeIPass Version:2.6.8
KeePassHttp Version:1.8.4.0
Chrome Version 39.0.2171.99 m
KeyPass 2.28

Is also stopped working for me too.

**Comment by fnkr** [comment]
OS: Windows 7
chromeIPass Version: 2.6.8
KeePassHttp Version: 1.8.4.0
Chrome Version: 40.0.2214.91
KeePass: 2.28

OS: Windows 8.1
chromeIPass Version: 2.6.8
KeePassHttp Version: 1.8.4.0
Chrome Version: 40.0.2214.91
KeePass: 2.28

+2

**Comment by fnkr** [comment]
I think it might has to do with this pull request: https://github.com/pfn/passifox/pull/309/files

**Comment by fnkr** [comment]
I tested it and if I undo #309 Ctrl+U is working again.

**Comment by abhikush** [comment]
How do I download the latest version with this fix? The version in chrome webstore is still 2.6.8

**Comment by fnkr** [comment]
@pfn Can you please upload the latest version to the chrome web store?
