### ISSUE TITLE
Keyboard Shortcuts no longer Functional on Chrome

### ISSUE THREAD

**Issue by shackrock** [pfn/passifox#356]
On chrome xtrl+shift+u and ctrl+shift+p used to force the autofill for username and pass, or password, respectively.

On the latest version of chrome, the P shortcut now opens up the print screen.  The U shortcut does nothing.

Thanks.

**Comment by prashker** [comment]
Can also confirm @shackrock issue. Been like this for quite a while now.

Chrome Version: 42.0.2311.11 dev-m
chromeIPass Version: 2.6.8
KeePassHttp Version: 1.8.4.0

**Comment by shackrock** [comment]
Any update from the team?

**Comment by HowellBP** [comment]
KeePassHTTP 1.8.4, Chrome 44.0.2403.39 beta-m (64-bit), chromeIPass 2.6.8

Still no keyboard shortcut functionality as of June 16th, 2015. Have not had keyboard functionality since KeePassHTTP 1.8.3.

**Comment by iandunn** [comment]
@HowellBP, can you test if `ctrl+shift+F6` works for username and password, and `ctrl+shift+F1` for password only?

**Comment by HowellBP** [comment]
@iandunn Yes, just tried it and it works. Is this change documented anywhere? A cursory search of the issues on github didn't show this change. Can the settings page for chromeiPass be updated to reflect the new keystrokes? Thanks.

**Comment by shackrock** [comment]
@iandunn I can confirm the same.  Any way to customize this keystroke while we're at it?

**Comment by prashker** [comment]
@iandunn Also works. Cool. Same stats as @HowellBP browser-wise and extension wise. On my end I'll just bind a keyboard macro to that combination but that's definitely not a global solution

Thanks for mentioning that though, TIL.

**Comment by iandunn** [comment]
I don't think it's documented anywhere, I just found it in one of the other half-dozen reports on this problem.

I'm not one of the maintainers, but @lukas-schulze or @pfn could make that change. I'm sure they're busy, so it'd probably help if you sent a pull request.
