### ISSUE TITLE
Possible creation of multiple uuid

### ISSUE THREAD

**Issue by oozaru-hunter** [pfn/passifox#368]
Following happened to me: I use Keepass2 and Keepass2Android and since some time chromelPass.
Today I loaded since some time my database in Keepass2Android and received a warning about multiple uuid (context: http://sourceforge.net/p/keepass/discussion/329220/thread/7e3fe63d).

I have created entries in my database with chromelPass. Could it be that chromelPass created mutpliple uuid? Is there a way to test it?

**Comment by pfn** [comment]
Not possible
