### ISSUE TITLE
repeated login attempts when already logged in

### ISSUE THREAD

**Issue by sixspot** [pfn/passifox#376]
Using Linux.
Google Chrome Version 41.0.2272.118 (64-bit)
KeepassHTTP  1.8.4
chromeIPass 2.6.8
KeePass 2.28
Linux

I have a icingaweb2 website running on a local server. Each time I focus on a tab for that website, chromeIPass tries to authenticate even though I have already logged in. I set it to automatic for now as a workaround, but see authentication popup notices on each focus.

**Comment by pfn** [comment]
Your page still contains a password field, that is the cause of the
prompting.

--

**Comment by sixspot** [comment]
I see the following HTML for the password on the login page. There's no instance of "password" in any of the other pages.  Could something in the javascript trigger an authentication attempt?

```<div class="element"><label for="form_login_password-konhawgmerfj" class="required">Password</label><input type="password" name="password" id="form_login_password-konhawgmerfj" value="" placeholder="...and your password" class="" aria-required="true" required=""></div>
```
login page http://pastebin.pw/zftebn#
a regular page http://pastebin.pw/z94mh7

**Comment by pfn** [comment]
Yes, javascript can and does generate password fields

--
