### ISSUE TITLE
not detecting any forms in passifox

### ISSUE THREAD

**Issue by cortopy** [pfn/passifox#393]
Just installed passifox in Firefox Linux(Ubuntu) and connected it using KeePassHttp.plgx. Everything seemed ok, but no form seems to be detected.

I've run all troubleshooting (title has now the URL for example), but I could also see that for Linux I should've used the .dll files. I'm not sure if it's too late now. I've now tried connecting with these and, again, connection is made. However, no forms are detected. 

I'm unable to reset all settings though as there is no config menu and I didn't get the encryption key popup to assign a name either. So it seems the browser will always remain with the same key. Is this why the .dll method does not work either?

**Comment by pfn** [comment]
Do not disable password manager

--

**Comment by cortopy** [comment]
What do you mean "password manager"? which one?

**Comment by pfn** [comment]
Do not disable the builtin password manager. Passifox is a storage
replacement

--

**Comment by cortopy** [comment]
Thanks!! That was the issue indeed. All working now.

Also, out of curiosity I went back to try with the KeePassHttp.plgx file and it works too. I don't know if this useful, but having seen in https://addons.mozilla.org/en-us/firefox/addon/passifox/ that for Linux .dll were necessary instead, I just wanted to report that .plgx works fine on my Ubuntu computer
