### ISSUE TITLE
"You use an old version of KeePassHttp. Please download the latest version from GitHub."... but how?

### ISSUE THREAD

**Issue by niknami** [pfn/passifox#395]
I'm using chromeIPass; I keep getting this warning but I'm not sure how to resolve it. What am I supposed to do?

**Comment by Maxqia** [comment]
http://lmgtfy.com/?q=keepasshttp+github

**Comment by niknami** [comment]
Thanks... my bad, not sure why I posted it here, must've followed the wrong link somewhere.
