### ISSUE TITLE
Ctrl-Shift-U stopped working a while ago

### ISSUE THREAD

**Issue by mehrdadn** [pfn/passifox#396]
I use chromeIPass. It used to be that Ctrl-Shift-U worked on Chrome, but for the past few months it's stopped working. Is it broken now, or has something happened? I'm on Chrome 43.0.2357.124 x64.

**Comment by shackrock** [comment]
There's another thread about this, but the dev changed it to control shift F6 for some reason, that is working most of the time for me now.

**Comment by shackrock** [comment]
For the record, in the latest release this has been removed from ctrl+F6 again and now is ctrl+U and ctrl+P like it used to be.

**Comment by mehrdadn** [comment]
Yup, that's why I closed the issue haha.
