### ISSUE TITLE
chromeipass - http auth requests are not autofilled

### ISSUE THREAD

**Issue by delize** [pfn/passifox#397]
These boxes:
[HTTP Auth](https://i.stack.imgur.com/9s062.png)

are not being automatically filled out in chromeipass. This was not the case with Firefox, it worked fine when I was using that browser, but chromipass does not fill in the authentication box. 

Using the following versions:
Chrome Version: 43 (Stable Channel)
chromeIPass Version:2.6.8
KeePassHttp Version:1.8.4.0
KeePass Version: 2.29

**Comment by pfn** [comment]
Chrome does not allow extensions to fill in the http auth dialog

--

**Comment by delize** [comment]
According to your documentation, you support it:
https://github.com/pfn/passifox/blob/master/documentation/chromeIPass.md#36-auto-fill-in-for-http-auth-requests

**Comment by pfn** [comment]
They are auto submitted, but the dialog does not get filled

--

**Comment by delize** [comment]
Do you know if there are any chrome/chromium bugs filed for this already to implement that type of behavior?

**Comment by pfn** [comment]
Any bugs opened would likely be closed wontfix due to the security nature
of http auth dialogs.

**Comment by delize** [comment]
Alright, well, that is a bummer. I guess I will close the ticket then. :(
