### ISSUE TITLE
PassIFox could not be verified for use in Firefox Developer Edition

### ISSUE THREAD

**Issue by schkovich** [pfn/passifox#426]
![passifox](https://cloud.githubusercontent.com/assets/1050649/10130576/0d508ccc-65ca-11e5-8623-afbd75342d6d.png)

More information on [verification](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox).

**Comment by alex-dot** [comment]
Today I updated my Firefox on Ubuntu and apparently unsigned plugins are now disabled by default and cannot be manually enabled through the GUI. I suppose that this will happen to most other users in the coming days as well, so I urge the owner to get this plugin verified ASAP!

As a temporary (!) workaround, the installation of unsigned addons can be reactivated by doing the following:
1. Open `about:config`
2. Search for `xpi`
3. Set `xpinstall.signatures.required` to `false`

**Comment by pfn** [comment]
#448
