### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by ccryx** [pfn/passifox#445]
Hi, I know that you have stated that you consider your code to be under the GPL in [this issue](https://github.com/pfn/passifox/issues/211).
I wrote a keepasshttp client in python that's heavily based on your javascript implementation in ChromeIPass and I want to put it on github (in fact, [I already did](https://github.com/ccryx/python-keephasshttpc), I was just about to add a license myself).
I would feel much more comfortable if you could add a LICENSE file stating that you license your code under the GPL (2? 3?) or another open source license.

If you want me to, I can add it (GPL3) myself and create a pull request.

**Comment by pfn** [comment]
Submit a pr for gpl v3, thanks

--

**Comment by ccryx** [comment]
Let me know if you want me to change anything.
