### ISSUE TITLE
PassIFox disabled in Firefox 43

### ISSUE THREAD

**Issue by drehren** [pfn/passifox#448]
Hi, from Firefox 44 onwards, it requires that all addons are signed.
Since PassIFox isn't, it is disabled.
The details are [here](https://wiki.mozilla.org/Addons/Extension_Signing).

-- EDIT
To enable it in Firefox 43, a preference (_xpinstall.signatures.required_ in about:config) must be changed.

**Comment by piotr-cz** [comment]
+1

**Comment by pfn** [comment]
To fix:

Go to https://addons.mozilla.org/en-US/firefox/addon/passifox/?src=search

Press "Add to Firefox" -- this will force firefox to re-download the signed version.

**Comment by piotr-cz** [comment]
I can confirm this _Add to Firefox_ resolves the issue.
Thank you!
