### ISSUE TITLE
PassiFox add-on is unverified, rendering it unusable in Firefox 43+

### ISSUE THREAD

**Issue by aairey** [pfn/passifox#450]
Today on start-up of Firefox, PassiFox was automatically disabled.
This is due to the fact that the add-on seems to be unverified.

Screenshot: ![firefox_screenshot](https://cloud.githubusercontent.com/assets/7644094/11918998/302420c0-a746-11e5-9ebb-2a7417ef6baa.png)

Details:
PassiFox 1.1.13
Firefox 43.0.1
Windows 10

More information: https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct

Looks like the add-on needs to be [submitted to AMO](https://developer.mozilla.org/en-US/Add-ons/Distribution).

**Comment by pfn** [comment]
Reinstall from amo

--

**Comment by pfn** [comment]
Duplicate of #448

**Comment by pfn** [comment]
Duplicate of #448
