### ISSUE TITLE
[Feature Request] Equal domain usage

### ISSUE THREAD

**Issue by marceldeglau** [pfn/passifox#453]
Hey there!

Today I have a feature request for you? Can you please the feature for equal domain use?

For example:
Saved url in keepass database: github.com
chromeIPass will now search for login forms at the whole domain: equal www.github.com http://github.com or https://github.com or sample.github.com

I want to hear form you about this idea ;)

Greetings, Marcel

**Comment by pfn** [comment]
It already does this

**Comment by marceldeglau** [comment]
Hey, oh nice, i doen't have seen this feature yet. Thank you for the fast support!
