### ISSUE TITLE
chromeIPass Error 105 more than one login was found, option to turn that off?

### ISSUE THREAD

**Issue by iarp** [pfn/passifox#458]
Whenever it doesn't autofill and you have to right click on the username/password box and select Fill User + Pass it'll pop-up saying Error 105 more than one login was found. Is it possible to stop that message from popping up, it's getting rather annoying to have to close it every time.

For example when logging into a Google account it never loads any of the accounts, I always have to right click and Fill User + Pass, then close the dialog and then go to the icon in the toolbar. I understand that doing the right click option requires i then go to the icon. A new person may not know that, which is why I'm asking if this can be turned into a selectable option. Thanks.

**Comment by GarretGallius** [comment]
Not a developer here, just fellow user.  In KeePass 2.31, when I visit:
Tools > KeePassHttp Options
I see a checkbox like this:
[ ] Return only best matching entries for an URL
    instead of all entries for the whole domain.

Hope that helps your situation or someone else reading this.

**Comment by iarp** [comment]
That modifies what items are being returned, but doesn't stop the pop-up which is a part of chromeIPass.

**Comment by namtab00** [comment]
well, if anyone's interested I added an option to redirect those message to console.log..

see https://github.com/pfn/passifox/pull/457

**Comment by zeromido** [comment]
Maybe it's too late to answer but I just signed up here today !
Try this:
1. Run Keepass.
2. Open "KeePassHttp Options..." by clicking "Tools" in Keepass window.
3. Click "Advanced" tab  then check "Always allow access to entries".
Here you got two choices:
First
If you want  a dropdown list appears which contains all available logins
Go to [chromeIPass Settings](chrome-extension://ompiailgknfdndiefoaoiligalphfdae/options/options.html)
check "Automatically fill-in single credentials entry."
Second
If you want to click on chromeIPass icon to view logins
Go to [chromeIPass Settings](chrome-extension://ompiailgknfdndiefoaoiligalphfdae/options/options.html)
Uncheck "Automatically fill-in single credentials entry."
I hope it works for you
Thanks

**Comment by iarp** [comment]
General -> Show These Settings Anyway -> Supress warnings and errors via alert. That will stop it now.
