### ISSUE TITLE
PassIFox could not be verified for use in Firefox.  Proceed with caution

### ISSUE THREAD

**Issue by irishatheist** [pfn/passifox#460]
This situation started about a month ago.  

Currently Firefox 43.0.4 on 64bit Windows 8.1, but occurs on other Windows variants too.

Can workaround by changing the preference xpinstall.signatures.required to false in the Firefox Configuration Editor (about:config page).

Can PassIFox get the signing required and a version bump?  Appreciated.

**Comment by pfn** [comment]
#448
