### ISSUE TITLE
ChromeIPass build instructions

### ISSUE THREAD

**Issue by marcelser** [pfn/passifox#461]
Hi,

Can anyone please provide build instructions for ChromeIPass?

Thx

**Comment by cracket** [comment]
+1 - especially that chrome shop has more recen version 2.6.8, and github sources stopped at version 2.6.7

**Comment by pfn** [comment]
Probably forgot to push the tag, will push Tuesday

**Comment by pfn** [comment]
cd chromeipass; zip -r ../cip.zip .
