### ISSUE TITLE
Can we expect a working PassIFox in the near future?

### ISSUE THREAD

**Issue by Eagle3386** [pfn/passifox#469]
Since 2014, there was no new version and with e10s (Electrolysis, i. e. Mozilla's multi-process architecture for Firefox) slated for release in April this year, I wonder if there's a new version coming or at least planned?

**Comment by pfn** [comment]
I have no plans to make changes for electrolysis. I welcome any volunteers
who would submit PRs which I will review.

**Comment by Eagle3386** [comment]
So, in other words the Firefox version of your extension simply dies - either when e10s hits the Release channel in April or when the WebExtensions API kills the current extension API model - as you simply don't care?

If that's true, that's a shame. I can't even express how much I hate Chrome for its disgusting UI, the whole workflow and many core work principles and I was happiy that PassIFox exists. But you seem to be just another add-on dev who switch sides completely and therefore the Firefox version soon dies.

Oh boy, I really feel bad now as I loved the integration that much. :(

**Comment by gene-pavlovsky** [comment]
@Eagle3386 As a developer I can understand pfn. I have a wife, a kid, bills to be paid. I have to work on jobs that can bring me income. Whatever free / open source things I do is limited by the free time I have. Of course I choose to spend that time working on something that can be useful to me personally. So if pfn doesn't use Firefox anymore, why do you expect him to dedicate a lot of attention to support the Firefox port? He probably has better things to do. At least in the open source world that doesn't mean death of a project - a new maintainer can step up and offer to take care of PassIFox in the future.

**Comment by Eagle3386** [comment]
@gene-pavlovsky while I do understand your point and respect pfn's decision for whatever reason he might has, it's simply my expression of frustration as I used PassIFox almost hourly and IMHO it's harder for an "outsider" to step in, understand the code and fix the corresponding lines than for pfn to do the same - granted, I do C#/.NET and no C++ which is why I can only partly imagine how much time it takes to fix the remaining bugs.

Maybe this is my call to step in, I don't know. Maybe if I find time..

**Comment by sammoth** [comment]
I am using PassIFox on FF Developer Edition using e10s on Linux right now and it is working fine. What problems are you having?

**Comment by Eagle3386** [comment]
Sorry for the delay. Tried it once again and it seems my profile wasn't totally clear or Nightly had a bug.
Anyway, with a fresh profile, everything worked as expected. Therefore, I'm closing this issue. Though, I'm looking forward to a dev picking up this extension and making it ready for the new add-on API system Mozilla is going to introduce.
