### ISSUE TITLE
chromeIPass has an issue with High ANSI chars

### ISSUE THREAD

**Issue by zeromido** [pfn/passifox#473]
Hi,
I've just found this issue
chromeIPass saves passwords with High ANSI chars incorrectly
e.g. 
this password: ¥µ¡²#ÎìÓ®±×èä¼ý-«`µý

is saved as: ����#��Ӯ�����-�`��
Please fix ASAP

Keepass 2.30
KeePassHttp 1.84
Chrome 49.0.2623.75 32bit
chromeIPass 2.6.8
Edit:
Issue was also repoted previously at
https://github.com/pfn/passifox/issues/242

**Comment by pfn** [comment]
probably caused by #47

**Comment by zeromido** [comment]
@pfn Okay, are you going to fix that?

**Comment by pfn** [comment]
probably not any time soon

**Comment by zeromido** [comment]
@pfn Would you even tell me what's the cause to that error (Current code is totally different from the commit you mentioned)

**Comment by pfn** [comment]
I don't know what the cause is, I can reproduce it and determine that there
is a bad conversion from latin1 to utf8

**Comment by zeromido** [comment]
Fixed by https://github.com/pfn/passifox/pull/491

**Comment by pfn** [comment]
Does this mean you verified this fix with keepass?

**Comment by zeromido** [comment]
@pfn Yes. I commented there see https://github.com/pfn/passifox/pull/491#issuecomment-211102984
