### ISSUE TITLE
Not adding new entries 

### ISSUE THREAD

**Issue by freekruemel** [pfn/passifox#475]
Hi
chromeIPass is not adding any new entries. It doesn't seem to recognize userid / password fields on new web pages. I can add new entries by using Firefox instead - once they are in the database they can be used fine by chromeIPass ...

chromeIPass Version:2.7.1
KeePassHttp Version:1.8.4.1
Chrome Version 49.0.2623.87 

Thanks.

**Comment by zeromido** [comment]
Okay, please
1. Create a new database and connect chromeIPass to it (using connect button).
2. Check "Activate password generator." box in chromeIPass options.
3. Go to [Facebook](https://www.facebook.com) and try to login and tell me what happened.

**Comment by freekruemel** [comment]
Hi 
Thanks for coming back to me on this issue. Tried the below – no change. Facebook login not added to DB.
Please have a look at the SWF video I created on the test.

More ideas?

Cheers.

[ChromeIpass.zip](https://github.com/pfn/passifox/files/190480/ChromeIpass.zip)

**Comment by zeromido** [comment]
Oh, I think I figured out what's your problem. You need to click chromeIPass icon when it's blinking (see 01:17 in you video). By default, the icon is blinking for 7500 milliseconds which is 7.5 seconds. You can change that by changing "Blink Time" value in chromeIPass options (and don't forget the value is in milliseconds!).
I hope that helps.

**Comment by freekruemel** [comment]
You are absolutely right. Works the way you described it. User error ... ;-)
But I kind of expected the entries to be created automatically. I changed the blink setting to 15000 just to make sure I see it ...
Thanks - much appreciated.

**Comment by zeromido** [comment]
You're welcome. Please close issue :)
