### ISSUE TITLE
Ctrl+Shift+U shortcut doesn't work on Linux

### ISSUE THREAD

**Issue by aripollak** [pfn/passifox#477]
Before 2.7.1, I had been able to use Ctrl+Shift+F6 for filling in username+password, but that no longer works after a1f909c. I can't use Ctrl+Shift+U since that's bound at a much lower level to let you type in Unicode characters by hex code. Would it make more sense to use Chrome's [keybinding API](https://developer.chrome.com/extensions/commands)?

**Comment by pfn** [comment]
http://superuser.com/questions/358749/how-to-disable-ctrlshiftu-in-ubuntu-linux

**Comment by pfn** [comment]
but if you want to submit a PR that implements the keybinding api, that might be useful.
