### ISSUE TITLE
Failed to update to KeePass 2.32 - KeePassHttp 1.8.4.1 - chromeIPass Version:2.7.1

### ISSUE THREAD

**Issue by rastony** [pfn/passifox#497]
I updated both KeePass and KeePassHttp from former version to the latest one.
KeePass does not recognize KeePassHttp any longer as a plugin.
That's happened with my 3 PC (Win7, Win10 native, Win10 upgraded from 8.1).
Even tried to re-install from chocolatey. Unsuccessful.
Of course KeePass was shutdown during upgrades and I have tried to restart it several times

KeePassHttp.plgx is indeed in "C:\Program Files (x86)\KeePass Password Safe 2" folder.
I noticed NEW KeePassHttp.plg 36 Kb.
Old KeePassHttp.plgx 154 Kb.
Any problem there?

What should I do? Consequently ChromelPass has stopped working...

**Comment by rastony** [comment]
FIXED !

I wasn't downloading the right KeePassHttp.plgx (DO NOT right click and Save As... from GitHub file listing. Go to the file, open it and save it.

I've learnt my lesson.

Sorry for the waste of time. Hope this could help others.

Keep the good work !

**Comment by rastony** [comment]
FIXED.
(user mistake)

**Comment by pfn** [comment]
You downloaded the wrong thing. Download the correct file.
