### ISSUE TITLE
ChromeIPass will not enter User or Passwords

### ISSUE THREAD

**Issue by rontpa3** [pfn/passifox#499]
ChromeIPass will not enter User or Passwords
Installation and connection of ChromeiPass and Keypass is complete. The connection message shows.
Can not login to any site using ChromeIPass
Repeatedly get error message: "No Login found"
As described in help tutor the Keypass icon in the system tray does not blink to confirm access.
Restarting Chrome does not help.
Keypass 2.32
ChromeIpass 2.71
KeypassHTTP 1.8.4.1

**Comment by zeromido** [comment]
First of all please [install the latest version of ChromeIPass, v2.7.2](https://chrome.google.com/webstore/detail/chromeipass/ompiailgknfdndiefoaoiligalphfdae)
Did you mess with any settings in KeePassHttp? If not, maybe entries URLs are wrong; ChromeIPass depends on entries URLs to fill credentials, you know.

**Comment by rontpa3** [comment]
Thanks zeromido,
The trick seems to be using the exact URL. This issue is resolved.
Instructions for installing and using ChromIpass could be a bit better.

**Comment by rontpa3** [comment]
Thanks, you have resolved this. The trick seems to be using the exact URL.
instructions for installing and using ChromIpass could be a bit better.
I have posted this and closed the issue on GitHub.

**Comment by zeromido** [comment]
Happy to help :)
