### ISSUE TITLE
ChromeIPass - Deprecation warning for KeyboardEvent.keyIdentifier

### ISSUE THREAD

**Issue by Arnavion** [pfn/passifox#521]
Chrome dev channel (v53) prints this warning in the browser console for the content script:

`'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5316065118650368 for more details. [chrome-extension://ompiailgknfdndiefoaoiligalphfdae/chromeipass.js:64]`

It's for the keydown handler that the content script registers for <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>P</kbd> and <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>U</kbd> - https://github.com/pfn/passifox/blob/364358b/chromeipass/chromeipass.js#L62-L74

`e.keyIdentifier == "U+0050"` would become `e.key === "KeyP"` and `e.keyIdentifier == "U+0055"` would become `e.key === "KeyU"` (or test both if you want back-compat or something).

**Comment by pfn** [comment]
Submit a PR please, thanks.
