### ISSUE TITLE
Stopped working on Firefox 49

### ISSUE THREAD

**Issue by jagmoreira** [pfn/passifox#528]
I recently updated to Firefox 49 (dev edition) and my logins no longer auto-fill.
If I right-click on the username/password fields I and press "Fill User & Pass" the fields are then populated and firefox offers to update the url entry, but the next time I visit the page the logins remain unfilled.

Is this a PassIFox or a KeePassHttp issue?

I tested this on:
- Win7 + FF 49.0a2 + PassIFox 1.2.0 + KeePassHttp 1.8.4.1 + Keepass 2.28
- OSX El Capitan + FF 49.0a2 + PassIFox 1.2.0 + KeepassX 2.0.2 ([eugenesan's fork](https://github.com/eugenesan/keepassx))

**Comment by harikattar** [comment]
in about:support, do you have multiprocess windows enabled?  I'm using 48, but when I force enable that I have to right-click on each field and chose fill name & pass.

**Comment by jagmoreira** [comment]
I have it enabled. But I've had multiprocess enabled for a while now and never had problems with PassIFox.

If I disable multiprocess the fields are still not auto-filled. However, right-clicking on the user field and pressing "Fill Name & Pass" fills both the username and password fields.

**Comment by bknickelbine** [comment]
I have also been having problems with auto-fill lately. I've switched to global auto-type for the time being.

Windows 10, FF49.0a2 & 50.0a1, PassIFox 1.2.0, KeePassHttp 1.8.4.1, Keepass 2.34

Because the right-click behavior is still working, it seems like something post FF48 broke the form sensing ability of PassIFox (rather than a problem with KeePassHttp).

**Comment by pfn** [comment]
I imagine it's because of the new multiprocess thing

**Comment by Quaturn** [comment]
@bknickelbine can you please tell me how to enable global auto-type? in Firefox?

**Comment by bknickelbine** [comment]
@Quaturn By pressing CTRL+ALT+A, KeePass will attempt an auto-type on the current window if its name matches one of your entries. If you require more granularity than that, you might look at trying KeePass Helper to insert more info into the window name.

**Comment by Quaturn** [comment]
@bknickelbine Thanks for the info :-D

**Comment by lukehop** [comment]
I have exactly the same issue that @jagmoreira describes. It still works if I right-click and choose "Fill User & Pass" or choose CTRL+ALT+A. It happened right after Firefox 49 (Dev Edn) updated itself. Would love a fix if anyone know what it causing it.

**Comment by GeorgeHahn** [comment]
I'm running with e10s disabled and I've been experiencing the same thing in Nightly for the past few months. The Fill User & Pass button shows a No Logins Found message, even on sites that previously worked.

I'm happy to dig in and debug this one, but I'm not sure where to start. Can you point me in a direction?

**Comment by lukehop** [comment]
I'm also experiencing the same problem. Would love to know of a fix. Am running Firefox Developer Edition 50.0a2 (2016-08-28). If I run the latest regular Firefox (45.3.0) it works fine. I've tried enabling and disabling multiprocess it has no effect.

**Comment by Obusmydealz** [comment]
Now, the final release of Firefox 49 causes the same problem to my setup. :( Can anyone fix it? Right-Click "Fill User & Pass" still works.

**Comment by ritzmann** [comment]
Same here, lots of people are going to notice now that 49 is released. The code hasn't been touched in three months. Is this addon still maintained?

**Comment by purejava** [comment]
Same here for latest Keepass, keepass-plugin-http and Firefox on Arch linux.
I noticed this a couple of days ago as the Arch linux machine is used more frequently.

This morning, I updated my Win 10 machine from Firefox 48.0.2 to 49.0.1 and keepass-plugin-http stopped working.
When I look at the preferences of Firefox and display the stored passwords (which usually displays the contents that are stored in my Keepass database) only a subset of all passswords is displayed. Lots are missing. And the displayed do not work either.

Symptom: when I open an URL with credential fields, keepass-plugin-http does not offer anything. Usually I doubleclick in the Username field, select the appropriate entry and the credentials get filled in.

Now no credentials are offered.

If you need more testing or further info please let me know.

**Comment by agsteele** [comment]
I was slow to try and work out if something was wrong with my Firefox/PassIFox/KeePass integration.  As with others login fields are not automatically populated since Firefox 49.0 but I can right click and select Fill User & Pass.

In addition, every time I enter a user/password combination by that means I get prompted to save the password as if nothing had been recorded in KeePass.  Clicking the remember/save button seems to make no difference.

**Comment by agsteele** [comment]
In issue #555 the author says he doesn't have time to work on Firefox issues. He does, though, invite help: 
> If someone puts together a pr to fix this, I will review, merge and release a new version
Anyone feel competent to help???

**Comment by agsteele** [comment]
New version of PassiFox has been rolled out which seems to fix this issue - see #555

**Comment by jagmoreira** [comment]
#555 does indeed fix this problem. However I now have the same issue as @agsteele where I'm being prompted to save passwords every time.
I'll close this issue anyway. Please see #555 for further developments.
