### ISSUE TITLE
Unable to start HTTPListener

### ISSUE THREAD

**Issue by delize** [pfn/passifox#530]
Hello, 

First off, I have already read [this](https://github.com/pfn/keepasshttp/blob/master/README.md#http-listener-error-message), it isn't of any help. Nothing is using port 19455, or any other ports I set to it, I don't have multiple instances/plugins in the Keepass directory.

So I googled around and found [this](https://stackoverflow.com/questions/14962334/httplistenerexception-access-denied-for-non-admins), and unfortunately, setting that (or running Keepass as administrator) got around the issue.

To explain my situation, I am running a Windows VM, and running KeePass and attempting to use KeePasshttp through the Virtual Network Interface so that I can run the httplistener on multiple systems within the network. 

So instead of using the listening address as localhost, I am setting it to 192.168.235.128.

No matter what I set the command to run in that link though:
0.0.0.0
192.168.235.128
etc

(anything besides 127.0.0.1 or localhost)

It fails to allow the Keepasshttp plugin to function.

**Comment by piotr-cz** [comment]
This popup seems to start to show up after I've updated keepass to `v2.36`

**Comment by numanair** [comment]
I am having this issue on v2.36 as well.
