### ISSUE TITLE
Remember credentials doesn't work on Chrome

### ISSUE THREAD

**Issue by RoggerFabri** [pfn/passifox#535]
When I enter a combination of user + passwords on a website that is not previous saved on KeePass, the icon on Chrome Toolbar blinks but when I click on it, nothing happens. I'm not able to save my credentials on KeePass, I can only retrive them... what I'm missing?

**Comment by zeromido** [comment]
If you're not using the latest version of chromeIPass, please [download it](https://chrome.google.com/webstore/detail/chromeipass/ompiailgknfdndiefoaoiligalphfdae).
If it didn't work, see comments in https://github.com/pfn/passifox/issues/490.
Hope this helps.

**Comment by RoggerFabri** [comment]
I just reinstalled Chrome and it worked! Thank you!

**Comment by zeromido** [comment]
Happy to help :)
