### ISSUE TITLE
PassIFox not autofilling (possibily related to Firefox Sync)

### ISSUE THREAD

**Issue by auanasgheps** [pfn/passifox#536]
Hi there,

I noticed that Firefox is not autofilling anymore my logins. If I right click and do **Fill User & Password**, it works fine. 

I am using PassIFox 1.2.0 on Windows 10, along with Firefox 47.0.1.

That's what I have discovered: the problem may be limited to me, although would be nice to know what's the problem.

I am using Firefox Sync. I discovered that **syncing my preferences** may the problem. 
A fresh new installation of Firefox works great, but as soon as I enable Firefox Sync, autofill dies. However, if I disable sync of my preferences, force the sync, install a new Firefox (used portable edition btw) and enable sync, this time settings won't be synced, and autofill works as always. All the rest is synced, including add-ons (none of them is the cause of the problem).

Now, my question is: can I debug passifox without being a developer? Is there a way to get some logs? 
I simply want to find the exact setting that blocks autofill to work.

**Comment by alienos** [comment]
For me the same thing. I use firefox 47 Linux Mint 18

**Comment by lukehop** [comment]
Same here. Firefox Dev Edn 49.0a2 (2016-08-01), any ideas how to fix it?

**Comment by blubbsy** [comment]
Can confirm the problem with fx 48.0.2  on Windows 7 x64. Over the contect menu it works without problems, but autofill fails.

**Comment by lukehop** [comment]
I switched back from Firefox Developer Edition to regular Firefox because it could autofill the form fields. This morning it updated to Firefox 49.0 and this behaviour is now happening in regular Firefox. So annoying

**Comment by cheuk-fung** [comment]
Same issue after upgrading to 49.0

**Comment by auanasgheps** [comment]
Hi,
On Firefox 49 my autofill is broken as well as you guys.
I had disabled _Sync My preferences_, but it does not make any difference now.

Is the project dead or something?

**Comment by auanasgheps** [comment]
A fix has been released, PassIFox 1.2.1 autofills correctly in Firefox 49+. However, I haven't tested it with _Preferences_ enabled in Firefox Sync. I have the funny feeling that I'll break again, they are two separate issues.
And the project for Firefox is kinda dead, the author stated in another issue that hasn't got time to maintain the Firefox plugin..
