### ISSUE TITLE
chromeIpass choosing wrong login box

### ISSUE THREAD

**Issue by miketa2016** [pfn/passifox#538]
I've got chromeIpass set up and it works fine almost everywhere, but one bank site in particular (www.capcomfcu.org) is giving me an issue.

It incorrectly detects a search box as the login box, and it detects the password box correctly.  When I try to manually pick the credentials field, I'm still not able to choose the proper login box.

![error](https://cloud.githubusercontent.com/assets/20625914/17084346/15815ac4-5189-11e6-8f76-a096b6eb1b5f.PNG)

Any suggestions?

**Comment by zeromido** [comment]
It's just because that the field type 'username' isn't one that chromeIPass recognizes.
I will submit a pull request to fix it.

**Comment by miketa2016** [comment]
Any idea how long it takes for this commit to be available?  It's been a
month so far, and Chrome won't let me make the change myself.

**Comment by zeromido** [comment]
The project admin prefers to add all commits in one pull request, and I'm running low on free time currently.
So, if you can't wait, just do the following:
Download the unpacked extension [here](https://www.dropbox.com/s/7fcqi9st87h6wao/chromeipass.zip?dl=1).
Unzip it to your desired folder and copy its path (D:\Extensions\chromeipass for example)
Navigate to chrome://extensions and check Developer mode box at the top-middle.
Click Load unpacked extension...
Paste the folder path (the one you copied in step 3), and click OK.
You can now use the extension normally. The only problem is that Chrome warns you about running extensions in developer mode every time you start it. 
This is a temporary solution; I will submit the PR as soon as possible.
Sorry for any inconvenience.

**Comment by miketa2016** [comment]
Hey any chance you could submit the PR?

**Comment by zeromido** [comment]
@miketa2016 I'm terribly sorry for the delay. I just submitted the PR.
