### ISSUE TITLE
How to never show - "KeePass database is not open"

### ISSUE THREAD

**Issue by brand404** [pfn/passifox#542]
I like to keep my KeePass closed when i dont need it for security reasons.  But because of that PassIFox is obsessed in reminding me that it is not open.  Can you modify this extension to give it a check box option labelled: "Always nag about database not open" so one can have the choice?

It's a simple fix.  In the file: **KeePassFox.jsm** on line 379 just comment it out or implement a an option check.  I can do it myself but the problem is that it makes the extension unverified and since Firefox 48 it is mandatory that all extensions be verified. :(

**Comment by pfn** [comment]
Submit a PR that checks a preference

**Comment by brand404** [comment]
UPDATE:  Fixed!  For anyone else in the future that might want a resolution... After reading through the code i found that this extension wisely includes customizable constants; one of which stops this specific (and annoying) notification spam.  Under **about:config** just look for: **extensions.passifox.notification.kpf-db-note** and set it to **false**.  Done.
