### ISSUE TITLE
HTTP Authentication vs Forms: Multiple Credentials on same URL

### ISSUE THREAD

**Issue by julianxhokaxhiu** [pfn/passifox#552]
As the title says, since I upgraded to Chrome 53, the extension is not providing an Auto-Login on HTTP Authentication prompt. even if the checkbox is checked ( as it was before ).

Should I do a further action? I always clear my Chrome data at the end of the day, but I did this also on Chrome 52, and never had an issue with that.

Although, on Form masks, the information is got correctly, and fileds are autofilled correctly.

Any known issue? I'm not able to find one here on Github. Thanks in advance :)

chromeIPass Version:2.7.2
KeePass 2.34
KeePassHttp Version:1.8.4.1
Chrome 53.0.2785.116 (official Build) m (a 64 bit)
Windows 10.0.14393

**Comment by julianxhokaxhiu** [comment]
Oh! I actually found that two credentials were matching and the extension was asking which one to use. So there's no technical issue here. Although, how can I flag something only for HTTP Access, and when only for Forms ? Is there a possibility?

**Comment by pfn** [comment]
there is not, no

**Comment by julianxhokaxhiu** [comment]
And is there a way to be implemented then? I'll try to take a look at the code later, maybe I can figure out a PR.
