### ISSUE TITLE
Can't connect to the database. Worked fine yesterday! (forbidden- 403)

### ISSUE THREAD

**Issue by Trigant** [pfn/passifox#554]
keepasshttp	1.8.4.1
keepass		2.34
chromeipass
chrome 		53.0.2785.116 m (64bit)
every page

it isn't possible to regain connection to the database. yesterday it worked. today, no connection at all.
the dev console texts, it would be forbidden error 403 on keepass.js
what's changed since yesterday??? Oo

**Comment by mendel129** [comment]
same here on firefox/win10... some windows update or something?

**Comment by Obusmydealz** [comment]
> what's changed since yesterday??? Oo
Release of FF 49?
I've also an issue since then, related to this one: https://github.com/pfn/passifox/issues/528

**Comment by Trigant** [comment]
Now it's working again. System restart helped- Sry for inconvinience
