### ISSUE TITLE
Chromeipass not respecting maxlength="" attribute

### ISSUE THREAD

**Issue by iarp** [pfn/passifox#556]
Is it at all possible to get the auto-fill to respect the maxlength="" attribute?

Somehow the autofiller is capable of filling more than maxlength allows.

The situation I found this in was on a government website. They didn't list anything as max password length so when I copied and pasted the password into the box on the website, the website automatically drops the rest of the string off after maxlength="" characters. Then when you would revisit the page, autofill would do it's thing and it would fail to login, however copying and pasting the password manually would drop the rest of the characters after the limit and let you login.

**Comment by pfn** [comment]
Possible yes, but I don't have time to do this, if someone puts together a
pr, it would be a reasonable merge
