### ISSUE TITLE
ChromeIPass randomly freezes Vivaldi (chromium fork) for several seconds

### ISSUE THREAD

**Issue by notnsane** [pfn/passifox#568]
It mostly happens when I'm out of focus and _then_ I focus on Vivaldi again, the whole browser freezes for several seconds (I get the kill/wait prompt and a blurry interface) and then I got control again.

Using latest Vivaldi's unstable snapshot, which uses latest Chromium (54)
Win 10 x64, Vivaldi 1.5.652.8 (Official Build) (64-bit)
Http plugin 1.8.4.1

**Comment by GwenDragon** [comment]
Cant confirm for Vivaldi 1.5.651.10 (32-Bit) on Win 10 x64.
No freeze of Vivaldi.

Which OS? Which Vivaldi version?
Any other extensions used?

**Comment by notnsane** [comment]
Win 10 x64, Vivaldi 1.5.652.8 (Official Build) (64-bit)
Http plugin 1.8.4.1

I'll try to get better repro but for now it's pretty random.

**Comment by notnsane** [comment]
I can confirm it's NOT the extension, it's something else. I'll close this (maybe the http plugin?), thanks!
