### ISSUE TITLE
KeepassHTTP.plgx not loaded in KeePass 1.32 - never did in previous versions

### ISSUE THREAD

**Issue by OldSchoolboy** [pfn/passifox#582]
Win 10
Keepass 1.32
Chrome 55.0.2883.87 m
and KeepassHTTP fromhttps://github.com/pfn/keepasshttp/blob/master/KeePassHttp.plgx?raw=true

of course dropped into the KeePass Directory: C:\KeePass-1.22 (kept updating KeePass into the old directory) but KeePass.EXE dates Jan 2nd 2017

After reading the thread in https://github.com/pfn/passifox/issues/339, the resolution there didn't help,
and I've opened a new one as KeePass is newer and it's Win10:

KeepassHTTP doesnt show up in Tools/Plugins (Item looks inactive, maybe since there are none).
ChromeIPass raises error KeePassHTTP not running.

I've tried ages ago with older version, and didn't work either, back then.

Any idea out there?

Thx

Old Schoolboy

**Comment by pfn** [comment]
KeePassHttp is only for KeePass 2

**Comment by OldSchoolboy** [comment]
Thanks!

That's should have been clear to me.

regards from the illiterate Scholboy
