### ISSUE TITLE
Update description to mention KeePassXC

### ISSUE THREAD

**Issue by k3a** [pfn/passifox#585]
Can you please update passifox description to mention it works with KeePassXC as well?

KeePassXC is a community edition of KeePassX which supports KeePassHttp and I like it more because it's native and I don't have to install and use Mono. I use it on Linux but they say it supports Mac OS X and Windows as well.

Thanks

**Comment by GuilloOme** [comment]
I already made an update in a fork but I am waiting the release of KeePassXC version 2.1.1 (which will re-enable the HTTP support) before proposing a pull-request…
See: https://github.com/GuilloOme/passifox

**Comment by k3a** [comment]
Ok, thanks. Also the description at Mozilla Addons needs to be updated https://addons.mozilla.org/en-US/firefox/addon/passifox/

**Comment by GuilloOme** [comment]
I just submitted the pull-request #589… But since the description on addons.mozilla.org is not related to the github repo, it has to be modified somewhere else.

**Comment by k3a** [comment]
I think @pfn itself will have to update addons.mozilla.org description :)
