### ISSUE TITLE
Passifox dosn't save new credentials to Keepass XC *SOLVED*

### ISSUE THREAD

**Issue by redzacke** [pfn/passifox#611]
Hi there,
first some informations:
MacOS 10.12.3
PassiFox 1.2.2
FireFox 52.0.1 (64-Bit)
KeePassHttp version: I don't know
KeePassXC version 2.1.3
   
In contradiction to its feature list and to ChromeIPass,
PassIFox gives no option to automaticly save a new username/password for e.g. "web.de", "cyberport.de" and so on into the Keepass - database.  

Any idea how it can be fixed? 

Anyway, there is no PassIFox - icon in FireFox's extension bar. 
I do not know if it has to be so or not. ChromeIPass has an icon in Chrome extension bar.
Maybe someone could explain me that,too?

Thanks for your time and help.

**Comment by redzacke** [comment]
So, after long research I got it :)

PassIFox does use FireFox's own Password manager. PassIFox only transmitts between FireFox and KeepassXC. That is possibly also the reason why you will not find an icon in the extension bar. But FireFox functionality saving passwords (Settings>Security) must be enabled!(*1 see below) Everytime FireFox asks you weather you like to save or update a username/password. Just click yes and it will be handed over to KeePass Database. 

*1 If you cannot enable it, one option is deleting FireFox's preferences Folder 
 (MacOS-Terminal: rm -R /Users/"username"/Library/Application\ Support/Firefox/)
 (Linux (ubuntu)-Terminal: rm -R /home/"username"/.mozilla/firefox/)
 (Windows Path to Folder: Make sure seeing hidden files!
 C:\Users\<Windows login/username>\Appdata\Roaming\Mozilla\Firefox\<Profilname> 
Attention! You will lose FireFox's configuration and all saved bookmarks! But if you have an FireFox account everything will be reloaded from the cloud. 

@pfn:
Am I right? 
Perhaps it might be useful to mention these differences in the official documentation for other users, changing over from ChromeIPass. So hopefully they are not as confused as I am was.

Cheers!

**Comment by pfn** [comment]
Yes, passifox is a storage backend for firefox. All password form fill
functionality is handled by firefox. (This may change when the web
extension becomes default due to multi-process)

**Comment by hausmaen** [comment]
THANK YOU! it worked for me.
