### ISSUE TITLE
PassIFox - Icon not visible in Firefox

### ISSUE THREAD

**Issue by GandertM** [pfn/passifox#635]
Extension = PassIFox 1.2.2
Browser = Firefox 54.0 (32-bit)
KeePassHttp = 1.8.4.2
KeePass = 2.36
Within Firefox the add-on is visible in about:addons.
But there is no icon visible in Firefox.
I do receive the credentials message though and the add-on is search and finding the correct un and pw, so it appears to be working.
And Firefox sync is broken.

**Comment by leManu** [comment]
Same here...

* PassiFox = 1.2.2
* Firefox = 54.0.1 (64 bits) on Windows 10
* KeePassXC = 2.2.0

KeePassHttp connection is working, "Fill User & Pass" works also, but PassIFox icon is not visible...

I repaired Firefox Sync by uninstalling PassIFox, disconnecting Sync, reinstalling PassIFox and reconfiguring it and then reconnecting Sync. Seems to work now.

**Comment by GandertM** [comment]
Thanks for the update IeManu.
After update to Firefox 54.0.1 (32-bit) I was able to restore sync by following your instructions.
PassIFox icon is still not visible though.

**Comment by Ajilis** [comment]
Extension = PassIFox 1.2.2
Browser = Firefox 54.0.1 (64-bit) Mac OS
KeePassXC = 2.2.0

there is no icon visible in Firefox.
so extension not usable
