### ISSUE TITLE
Passifox not visible in firefox macOS

### ISSUE THREAD

**Issue by Ajilis** [pfn/passifox#643]
Extension = PassIFox 1.2.2
Browser = Firefox 54.0.1 (64-bit) Mac OS
KeePassXC = 2.2.0

there is no icon visible in Firefox.
so extension not usable

**Comment by kDot** [comment]
I came here to report this. +1

Extension = PassIFox 1.2.2
Browser = Firefox 54.0.1 (64-bit) Mac OS
KeeWeb = 1.5.4
