### ISSUE TITLE
When Firefox 57 compatible addon will be published

### ISSUE THREAD

**Issue by MuhammedKpln** [pfn/passifox#654]
Hello, i just wondering about when you guys will publish the extension for firefox57. I compiled from the source and it works good i just wondering when it will bi available at Mozilla Addons page or an beta signed version that we can install on firefox nightly or later.

**Comment by Christoph-Wagner** [comment]
You should follow this PR: https://github.com/pfn/passifox/pull/595

**Comment by craftycorvid** [comment]
You should look at this project instead: https://github.com/smorks/keepasshttp-connector

Edit: And now it's on AMO: https://addons.mozilla.org/en-US/firefox/addon/keepasshttp-connector/
