### ISSUE TITLE
firefox crashes when opening a site with http basic auth

### ISSUE THREAD

**Issue by whysthatso** [pfn/passifox#659]
i can make available the firefox crash report, if that helps.

**Comment by samuraiii** [comment]
It is related to Passifox/ublock (umatrix) add-on incompatibility,,, It works when you disable one of mentioned plug-ins,
S

**Comment by whysthatso** [comment]
will not reproduce as i've moved on to keepasshttp-connector. will close for now.

**Comment by hockeymikey** [comment]
@samuraiii Agreed. I can reproduce with disabling one of them fixes it.
