### ISSUE TITLE
Support of Firefox Quantum

### ISSUE THREAD

**Issue by kepicorp** [pfn/passifox#660]
Hi Everyone,

Is there any plan to support *firefox* quantum in the near future? It's about to be release as the standard FF in a month or so.
I would happy to **contribute**.

Cheers,

**Comment by maxbbender** [comment]
+1

**Comment by linyubin** [comment]
+1

**Comment by jgottfried** [comment]
https://github.com/smorks/keepasshttp-connector

**Comment by Owyn** [comment]
Quantum went stable and was auto-updated to for users

**Comment by jgottfried** [comment]
Yes, and quantum removed the API that passIFox was built on. There won't be an update for Quantum. pfn has stated that they are no longer interested in maintaining this extension. So there haven't been any code change to this repository for 8 months.
This has been known for months, too. People worked on compatibility with multi-process Firefox and Quantum (more importantly WebExtensions). See bug #595 

Unfortunately there was no reply by the maintainer of this repository to hand over the reigns of the project so it was done under a new name, see my link above.

**Comment by kepicorp** [comment]
Thanks for your answer

**Comment by MatrixFr** [comment]
what alternative solution now?! :'(

**Comment by taurus-forever** [comment]
As pointed here https://github.com/pfn/passifox/pull/595#issuecomment-344444250, you can use "keepasshttp-connector" from https://addons.mozilla.org/en-US/firefox/addon/keepasshttp-connector/

**Comment by unalignedcoder** [comment]
keepasshttp-connector is a port of chromeIPass, which works out of the box on Quantum.  
The two extensions are identical. The problem with both is, they cannot handle the two-step login with Google. What's worse, the keyboard shortcut that is supposed to help to load the username is conflicting with the "merge windows" command which in Quantum (who knows why) cannot be remapped. 
This seems like a tiny change (map the fill-in command to a different set of keystrokes) and yet neither mantainer of the two extension has bothered to correct it. 
It doesn't look good.
