### ISSUE TITLE
PassIFox 1.2.2 disabled under Firefox 57 (Quantum)

### ISSUE THREAD

**Issue by MaikHerrmann** [pfn/passifox#663]
Hi,

today I installed Firefox 57 (Quantum). Unfortunately PassIFox 1.2.2 shows up as disabled now in the Add-ons Manager. It also has the label "legacy".

My KeePassHttp version is 1.8.4.2. Is there any chance to get PassIFox up and running again with the new Firefox Quantum?

Thanks,
Maik.

**Comment by jgottfried** [comment]
Please read all the other issues before opening a new one.
This is the most asked thing this past month, and the answer is always the same:

https://github.com/smorks/keepasshttp-connector

Firefox does no longer support the API this add-on used. That's what the "legacy" means. It's been known for months and people have come up with an alternative, but it's no longer PassIFox.

**Comment by MaikHerrmann** [comment]
Okay, thanks for the very quick reply. The suggested alternative is working fine.
