### ISSUE TITLE
passifox not working with new Firefox version

### ISSUE THREAD

**Issue by ghost** [pfn/passifox#665]
Since I updated Firefox some days ago, the plugin of passifox is not working anymore.

**Comment by agsteele** [comment]
Indeed, I fear that this may mean the end of PassIFox but we can hope...

**Comment by jgottfried** [comment]
Look at the other issues, you're not the first to ask this. It was not necessary to open a new issue.
#660 #595 

TL;DR: https://github.com/smorks/keepasshttp-connector is what you want.
