### ISSUE TITLE
Automatically unlock database if closed

### ISSUE THREAD

**Issue by piegamesde** [pfn/passifox#679]
My database locks automatically after 5 Minutes. When I want to sign in:
- I switch to KeePass
- I unlock the database
- I go back back to Chrome, tell the extension to reload
- and reload the page (or click "redetect credentials fields")

Instead I'd like to have:
- ChromeIPass detects that the page has a password form and that the data base is closed.
- ChromeIPass tells KeePass to unlock the database, and the password dialog pops up
- I enter my password
- ChromeIPass detects that the database is now unlocked and fills in the password.

Is this possible?

**Comment by Mark-Booth** [comment]
Be careful what you wish for. I've been forced to live with this behaviour with other browser extensions and it can be incredibly annoying.

Certainly if this were to be offered, I would want it to be configurable, and I would disable it.

**Comment by piegamesde** [comment]
It is even more annoying if you have to do four additional things in addition to just typing in the password.

**Comment by Mark-Booth** [comment]
This is why I suggested it be an option.

I find it annoying having dialogs pop up over what I'm trying to do, while you think not having them pop up is more annoying. In actuality, you may well find it more annoying than you expect, hence my comment that you be careful what you wish for.

Selfishly, I don't want my user experience to suffer in order that your user experience might (or might not) be enhanced.

**Comment by piegamesde** [comment]
I'm a great fan of making things optional, so this feature should be too. Apparently, the database can be unlocked by calling `keepass --unlock-all` and it will do exactly what I want.

This will require a list of URLs to be stored by ChromeIPass so that it can find out when to ask for unlocking the database though.

For now, I'll make a global shortcut for that command as a workaround and it will make it one step faster.

**Comment by piegamesde** [comment]
In the KeePassHTTP options, there is a checkbox "Request for unlocking the database if it is locked" and it does exactly what I need.
