### ISSUE TITLE
chromeIPass high cpu usage

### ISSUE THREAD

**Issue by jankei** [pfn/passifox#681]
CPU usage is very high on updated version of Chrome - Version 67.0.3396.62 (Official Build) (64-bit) 
on macOS High Sierra

**Comment by Vlatombe** [comment]
Seems to be a chrome bug https://bugs.chromium.org/p/chromium/issues/detail?id=848210

**Comment by jankei** [comment]
This issue was resolved with the last update of chrome. Thanks @Vlatombe for pointing that out
