### ISSUE TITLE
PassIFox for Quantum 61.0 (x64)

### ISSUE THREAD

**Issue by cloudmaker97** [pfn/passifox#684]
Please provide support for newer versions of firefox.

**Comment by kripskroll** [comment]
Latest Firefox version need development with WebExtensions instead of XUL.
Do you consider it ?

**Comment by quantrung9** [comment]
Personally, this is the best alternatives I've found till now:
https://github.com/smorks/keepassnatmsg (alternative to KeePassHTTP)
https://github.com/keepassxreboot/keepassxc-browser (alternative to PassIFox)
Follow their instructions carefully to make it works.

**Comment by pashamcr** [comment]
> 
> 
> Please provide support for newer versions of firefox.

https://github.com/pfn/passifox/pull/595#issuecomment-332429269
https://addons.mozilla.org/en-US/firefox/addon/keepasshttp-connector/
