### ISSUE TITLE
Request: Better URL matching for ChromeIPass

### ISSUE THREAD

**Issue by Owyn** [pfn/passifox#69]
If url is set to mysite.com then it would match any page on mysite.com but if url is set to mysite.com/adminpangel then it would match any page again, so on mysite.com/userlogin will be matched for both mysite.com and mysite.com/adminpanel passes in KeePass, now if I have those two passes in my keepass it won't fill up automaticly.

Suggestion:

Make it possible that if you set keepass entry with URL: "mysite.com/somepage" - it would match only that page and if there it is an entry for "mysite.com" it won't match if there is an match for this specific page.

**Comment by lusitania** [comment]
This doesn't quite work as expected. Lets take the example of a self-hosted GitLab where you have your login URL gitlab.mycorp.com/users/sign_in. Lets also suppose you are an admin and its your job to manage user logins via /admin/users/username/.

The account credentials of the user I edit are overwritten by my own credentials although the URL doesn't match. In this case "no credentials" would have been the best match.
